# Generated by Django 5.2.1 on 2026-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_role_eventimage_event_allowed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='event_app.role'),
        ),
    ]
