# Generated by Django 5.2.1 on 2026-02-18 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_add_event_fields_remove_unused_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='expired_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='agenda',
        ),
        migrations.AddField(
            model_name='event',
            name='building',
            field=models.CharField(blank=True, help_text='Məsələn: Əsas korpus', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_side',
            field=models.CharField(blank=True, help_text='Tədbiri keçirən tərəf', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(blank=True, help_text='Məsələn: 302 və ya Akt zalı', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EventAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField(help_text='Fəaliyyətin başlama saatı')),
                ('action', models.CharField(help_text='Məsələn: Açılış nitqi və ya Coffee Break', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='event_app.event')),
            ],
            options={
                'ordering': ['time_slot'],
            },
        ),
        migrations.CreateModel(
            name='AllowedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('group_name', models.CharField(blank=True, help_text='Könüllü: Qrup adı (məsələn, 601.21)', max_length=100, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_participants', to='event_app.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
