# Generated by Django 6.0.2 on 2026-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_rename_expired_date_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant_count',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
